### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by trashbirdecology** [trashbirdecology/bbsebird#2]
**To do** 
- [ ] create a lookup table for linking AOU codes, bbsAssistant::species_list, and eBird filenames (spp.abbr)
- [ ]  create a test within `id_ebird_files` or `munge_ebird_data` to ensure that the sampling_relMM-YYYY matches the MM-YYYY on the observations  
- [ ] add function to create a single data table for ebird and bbs counts/covars
- [ ] fix binding variables warnings (need to see which are worth adding to globalVariables())
- [ ] fix make_bbs_spatial to allow data integration over the spatial grid for people without access to route shapefiles (and add note on obtaining/access for shapefiles...)
- [ ] update README to include data munging + analysis + eBird and BBS route file requirements, download instructions, and filepaths. 
- [ ] test full EBD file sampling on an HPC (run out of RAM when trying to grab obs for 1 spp and all of US)
